#!/usr/bin/env bash
# One-time dependency setup for XYORAS Access.
#
#   scripts/bootstrap.sh
#
# Installs:
#   libctrpf   (CTRPluginFramework, the version with the Sound API)  -- pacman
#   3gxtool    (builds .3gx from .elf + .plgInfo)                    -- pacman
#   libncsnd   (CSND audio backend)                                  -- source
#   libcwav    (BCWAV playback over CSND)                            -- source
#   espeak-ng  (speech synthesis)                                    -- source
#
# pacman lives in devkitPro MSYS2. If this script cannot find it, run the
# pacman half from C:/devkitPro/msys2/msys2_shell.bat and re-run here.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Re-exec inside devkitPro MSYS2 if needed; see msys-guard.sh for why.
# shellcheck source=msys-guard.sh
source "${SCRIPT_DIR}/msys-guard.sh"
# shellcheck source=env.sh
XYORAS_ENV_QUIET=1 source "${SCRIPT_DIR}/env.sh"

# Pinned versions. Bump deliberately and record the change in
# "AI docks/12-research-log.md".
LIBCTRPF_PKG="libctrpf"          # expected 0.8.0.r1444-1 or newer
GXTOOL_PKG="3gxtool"             # expected 1.3-1 or newer
ESPEAK_NG_REPO="https://github.com/espeak-ng/espeak-ng"

# Pinned to a release tag, deliberately.
#
# eSpeak loads compiled voice data (phondata, en_dict, ...) at runtime, and that
# data is generated by HOST tools during a normal build. We cross-compile, so
# those tools cannot run for our target -- we take the data from an eSpeak NG
# install instead. The library and its data must be the same version, so
# pinning the source to a released tag is what keeps the two in step.
ESPEAK_NG_TAG="1.52.0"
LIBCWAV_REPO="https://github.com/PabloMK7/libcwav"
LIBNCSND_REPO="https://github.com/mariohackandglitch/libncsnd"

# A local eSpeak NG clone that may already exist on this machine. Using it
# saves a large download and works offline.
ESPEAK_LOCAL_HINT="${HOME}/Documents/llm experiments/misk/wii project/espeak-ng"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERR\033[0m %s\n' "$*" >&2; exit 1; }

mkdir -p "${XYORAS_THIRD_PARTY}"

# -----------------------------------------------------------------------------
# 1. pacman repositories
# -----------------------------------------------------------------------------

find_pacman() {
    if command -v pacman >/dev/null 2>&1; then
        command -v pacman
        return 0
    fi
    for p in "${DEVKITPRO}/msys2/usr/bin/pacman.exe" "/c/devkitPro/msys2/usr/bin/pacman.exe"; do
        [ -x "$p" ] && { echo "$p"; return 0; }
    done
    return 1
}

find_pacman_conf() {
    for c in "${DEVKITPRO}/msys2/etc/pacman.conf" "/c/devkitPro/msys2/etc/pacman.conf" /etc/pacman.conf; do
        [ -f "$c" ] && { echo "$c"; return 0; }
    done
    return 1
}

add_repo() {
    local conf="$1" name="$2" server="$3"
    if grep -Fxq "[${name}]" "${conf}"; then
        log "pacman repo [${name}] already present"
        return 0
    fi
    log "adding pacman repo [${name}]"
    printf '\n[%s]\nServer = %s\nSigLevel = Optional\n' "${name}" "${server}" >> "${conf}"
}

PACMAN="$(find_pacman || true)"
PACMAN_CONF="$(find_pacman_conf || true)"

if [ -n "${PACMAN}" ] && [ -n "${PACMAN_CONF}" ]; then
    if [ -w "${PACMAN_CONF}" ]; then
        add_repo "${PACMAN_CONF}" "thepixellizeross-lib" "https://thepixellizeross.gitlab.io/packages/any"
        add_repo "${PACMAN_CONF}" "thepixellizeross-win" "https://thepixellizeross.gitlab.io/packages/x86_64/win"
    else
        warn "cannot write ${PACMAN_CONF} — add the ThePixellizerOSS repos manually (see 'AI docks/07-build-environment.md')"
    fi

    log "syncing package databases"
    "${PACMAN}" -Sy --noconfirm || warn "pacman -Sy failed; continuing"

    log "installing ${LIBCTRPF_PKG} and ${GXTOOL_PKG}"
    "${PACMAN}" -S --needed --noconfirm "${LIBCTRPF_PKG}" "${GXTOOL_PKG}" \
        || warn "pacman install failed — run this script from devkitPro MSYS2"
else
    warn "pacman not found. Run this script from C:/devkitPro/msys2/msys2_shell.bat,"
    warn "or install ${LIBCTRPF_PKG} and ${GXTOOL_PKG} by hand."
fi

# -----------------------------------------------------------------------------
# 2. Source dependencies
# -----------------------------------------------------------------------------

clone_or_update() {
    local url="$1" dir="$2"
    if [ -d "${dir}/.git" ]; then
        log "$(basename "${dir}"): already present, fetching"
        git -C "${dir}" fetch --depth 1 origin >/dev/null 2>&1 || warn "fetch failed for ${dir} (offline?)"
    else
        log "cloning $(basename "${dir}")"
        git clone --depth 1 --recursive "${url}" "${dir}"
    fi
}

# eSpeak NG — prefer an existing local clone to avoid a large download.
if [ -d "${ESPEAK_NG_DIR}/.git" ]; then
    log "espeak-ng: already present at ${ESPEAK_NG_DIR}"
elif [ -d "${ESPEAK_LOCAL_HINT}/.git" ]; then
    # Clone from the local path rather than a file:// URL — the path contains
    # spaces, which git will not accept in a URL. A local clone also hardlinks
    # objects instead of copying them, so this is near-instant.
    log "espeak-ng: cloning from the local copy at ${ESPEAK_LOCAL_HINT}"
    git clone "${ESPEAK_LOCAL_HINT}" "${ESPEAK_NG_DIR}"
    git -C "${ESPEAK_NG_DIR}" remote set-url origin "${ESPEAK_NG_REPO}"
else
    clone_or_update "${ESPEAK_NG_REPO}" "${ESPEAK_NG_DIR}"
fi

# Pin to the tag that matches the voice data we ship.
if git -C "${ESPEAK_NG_DIR}" rev-parse -q --verify "refs/tags/${ESPEAK_NG_TAG}" >/dev/null 2>&1; then
    current="$(git -C "${ESPEAK_NG_DIR}" describe --tags --exact-match 2>/dev/null || echo "")"
    if [ "${current}" != "${ESPEAK_NG_TAG}" ]; then
        log "espeak-ng: checking out ${ESPEAK_NG_TAG}"
        git -C "${ESPEAK_NG_DIR}" checkout -q "${ESPEAK_NG_TAG}"
    else
        log "espeak-ng: already at ${ESPEAK_NG_TAG}"
    fi
else
    warn "espeak-ng: tag ${ESPEAK_NG_TAG} not found; staying on the current checkout"
fi

clone_or_update "${LIBNCSND_REPO}" "${XYORAS_THIRD_PARTY}/libncsnd"
clone_or_update "${LIBCWAV_REPO}"  "${XYORAS_THIRD_PARTY}/libcwav"

# -----------------------------------------------------------------------------
# 3. Build and install the audio libraries into $DEVKITPRO
# -----------------------------------------------------------------------------

install_lib() {
    local dir="$1" name="$2"
    if [ -f "${DEVKITPRO}/${name}/lib/lib${name#lib}.a" ]; then
        log "${name}: already installed"
        return 0
    fi
    log "building and installing ${name}"
    ( cd "${dir}" && dkp_make install ) || warn "${name} build failed — see 'AI docks/07-build-environment.md'"
}

install_lib "${XYORAS_THIRD_PARTY}/libncsnd" "libncsnd"
install_lib "${XYORAS_THIRD_PARTY}/libcwav"  "libcwav"

# -----------------------------------------------------------------------------
# 4. Report
# -----------------------------------------------------------------------------

log "verifying"
check() {
    if [ -e "$2" ]; then printf '  \033[1;32mok\033[0m   %-12s %s\n' "$1" "$2"
    else                 printf '  \033[1;31mmiss\033[0m %-12s %s\n' "$1" "$2"; fi
}

check "libctrpf"  "${DEVKITPRO}/libctrpf/lib/libctrpf.a"
check "libcwav"   "${DEVKITPRO}/libcwav/lib/libcwav.a"
check "libncsnd"  "${DEVKITPRO}/libncsnd/lib/libncsnd.a"
check "libctru"   "${CTRULIB}/lib/libctru.a"
check "espeak-ng" "${ESPEAK_NG_DIR}/CMakeLists.txt"
if command -v 3gxtool >/dev/null 2>&1 || [ -x "${DEVKITPRO}/tools/bin/3gxtool.exe" ]; then
    printf '  \033[1;32mok\033[0m   %-12s\n' "3gxtool"
else
    printf '  \033[1;31mmiss\033[0m %-12s\n' "3gxtool"
fi

log "bootstrap done — next: scripts/build-espeak-3ds.sh"
