#!/usr/bin/env bash
# Builds plugin-screenreader/ScreenReader.3gx and its test host app.
#
#   scripts/build-screenreader.sh [--clean]
#
# Requires scripts/bootstrap.sh and scripts/build-espeak-3ds.sh to have run,
# same as build-plugin.sh -- the screen reader links the same speech stack.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=msys-guard.sh
source "${SCRIPT_DIR}/msys-guard.sh"
# shellcheck source=env.sh
XYORAS_ENV_QUIET=1 source "${SCRIPT_DIR}/env.sh"

PLUGIN_DIR="${XYORAS_ROOT}/plugin-screenreader"
TESTAPP_DIR="${PLUGIN_DIR}/testapp"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*" >&2; }

if [ "${1:-}" = "--clean" ]; then
    log "cleaning"
    dkp_make -C "${PLUGIN_DIR}" clean
    dkp_make -C "${TESTAPP_DIR}" clean
    exit 0
fi

log "plugin"
dkp_make -C "${PLUGIN_DIR}"

log "test host app"
dkp_make -C "${TESTAPP_DIR}"

# Package as a .cxi (NCCH application), NOT just a .3dsx. CTRPF aborts inside a
# homebrew process; it needs a real application process with an ExHeader.
# See "AI docks/15-home-menu-screen-reader.md".
log "packaging test host as .cxi"
( cd "${TESTAPP_DIR}" && makerom -f ncch       -rsf testapp.rsf -elf testapp.elf -icon testapp.smdh       -o testapp.cxi ) || die "makerom failed"

# The plugin hooks this symbol by address, and the address moves whenever the
# test app is rebuilt. Keep screenreader.cfg in step automatically rather than
# leaving a stale address to debug.
ELF="${TESTAPP_DIR}/testapp.elf"
if [ -f "${ELF}" ]; then
    addr="$(arm-none-eabi-nm "${ELF}" | awk '/ sr_draw_item$/ {print $1}')"
    if [ -n "${addr}" ]; then
        cat > "${PLUGIN_DIR}/screenreader.cfg" <<CFG
# Generated by scripts/build-screenreader.sh -- do not edit by hand.
# Address of sr_draw_item() in testapp.elf; changes on every testapp rebuild.
hook_addr = 0x${addr}
CFG
        log "hook_addr = 0x${addr}"
    else
        warn "sr_draw_item not found in ${ELF}; screenreader.cfg left alone"
    fi
fi

echo
log "built:"
ls -la "${PLUGIN_DIR}"/ScreenReader.3gx "${TESTAPP_DIR}"/testapp.3dsx 2>/dev/null || true
