/*
 * XYORAS Access -- English name lookups.
 * Copyright (C) 2026 XYORAS Access contributors. GPL-3.0; see LICENSE.
 *
 * The tables themselves are generated by tools/gen_name_tables.py. Always use
 * these accessors rather than indexing the arrays: an out-of-range index from
 * a bad memory read must produce "unknown", not a crash.
 */
#ifndef XYORAS_NAMES_HPP
#define XYORAS_NAMES_HPP

#include "xyoras/common.hpp"

namespace xyoras { namespace names {

    extern const char *const kSpecies[];
    extern const u32 kSpeciesCount;
    extern const char *const kMoves[];
    extern const u32 kMovesCount;
    extern const char *const kAbilities[];
    extern const u32 kAbilitiesCount;
    extern const char *const kItems[];
    extern const u32 kItemsCount;

    /// Bounds-checked lookup. Never returns null.
    inline const char *Lookup(const char *const table[], u32 count, u32 index)
    {
        if (index >= count)
            return "unknown";
        const char *s = table[index];
        return (s != nullptr && s[0] != '\0') ? s : "unknown";
    }

    inline const char *Species(u32 index) { return Lookup(kSpecies, kSpeciesCount, index); }
    inline const char *Move(u32 index) { return Lookup(kMoves, kMovesCount, index); }
    inline const char *Ability(u32 index) { return Lookup(kAbilities, kAbilitiesCount, index); }
    inline const char *Item(u32 index) { return Lookup(kItems, kItemsCount, index); }

}} // namespace xyoras::names

#endif
